# -*- coding: utf-8 -*-
"""Bank_Note_Authentication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fM-hG_6k-qA8-8QuXwjzSFU-qN94vGID
"""

import lazypredict
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset= pd.read_csv('BankNote_Authentication.csv')

dataset.head()

dataset.isna().sum()

X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

print(X)

print(y)

dataset.describe()

dataset.info()

sns.pairplot(dataset)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))

import pickle
pickle_out= open("classifier.pkl", "wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()